# Generated by Django 4.1.1 on 2023-03-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_itemtype_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='Item',
        ),
        migrations.AlterModelTable(
            name='itemtype',
            table='ItemType',
        ),
    ]
