# Generated by Django 4.1.1 on 2023-03-17 11:50

from django.db import migrations

def create_initial_data(apps, schema_editor):
    Item = apps.get_model('backend', 'Item')
    ItemType = apps.get_model('backend', 'ItemType')

    ItemType.objects.create(name='Internet')
    ItemType.objects.create(name='Kamera')
    ItemType.objects.create(name='TV')
    ItemType.objects.create(name='Egyéb')


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_installstatus_personaldata_repairstatus_user_fname_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
